// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: cache/pkg/api/grpc/proto/schema/cache.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CacheGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetRequest) Reset() {
	*x = CacheGetRequest{}
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetRequest) ProtoMessage() {}

func (x *CacheGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetRequest.ProtoReflect.Descriptor instead.
func (*CacheGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescGZIP(), []int{0}
}

func (x *CacheGetRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type CacheGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheGetResponse) Reset() {
	*x = CacheGetResponse{}
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheGetResponse) ProtoMessage() {}

func (x *CacheGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheGetResponse.ProtoReflect.Descriptor instead.
func (*CacheGetResponse) Descriptor() ([]byte, []int) {
	return file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescGZIP(), []int{1}
}

func (x *CacheGetResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CacheSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSetRequest) Reset() {
	*x = CacheSetRequest{}
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSetRequest) ProtoMessage() {}

func (x *CacheSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSetRequest.ProtoReflect.Descriptor instead.
func (*CacheSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescGZIP(), []int{2}
}

func (x *CacheSetRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *CacheSetRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CacheDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheDeleteRequest) Reset() {
	*x = CacheDeleteRequest{}
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheDeleteRequest) ProtoMessage() {}

func (x *CacheDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheDeleteRequest.ProtoReflect.Descriptor instead.
func (*CacheDeleteRequest) Descriptor() ([]byte, []int) {
	return file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescGZIP(), []int{3}
}

func (x *CacheDeleteRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

var File_cache_pkg_api_grpc_proto_schema_cache_proto protoreflect.FileDescriptor

const file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDesc = "" +
	"\n" +
	"+cache/pkg/api/grpc/proto/schema/cache.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x0fCacheGetRequest\x12\x1c\n" +
	"\tshortCode\x18\x01 \x01(\tR\tshortCode\"$\n" +
	"\x10CacheGetResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"A\n" +
	"\x0fCacheSetRequest\x12\x1c\n" +
	"\tshortCode\x18\x01 \x01(\tR\tshortCode\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"2\n" +
	"\x12CacheDeleteRequest\x12\x1c\n" +
	"\tshortCode\x18\x01 \x01(\tR\tshortCode2\xb6\x01\n" +
	"\fCacheService\x124\n" +
	"\x03Get\x12\x15.main.CacheGetRequest\x1a\x16.main.CacheGetResponse\x124\n" +
	"\x03Set\x12\x15.main.CacheSetRequest\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\x06Delete\x12\x18.main.CacheDeleteRequest\x1a\x16.google.protobuf.EmptyB\tZ\a.;protob\x06proto3"

var (
	file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescOnce sync.Once
	file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescData []byte
)

func file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescGZIP() []byte {
	file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescOnce.Do(func() {
		file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDesc), len(file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDesc)))
	})
	return file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDescData
}

var file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cache_pkg_api_grpc_proto_schema_cache_proto_goTypes = []any{
	(*CacheGetRequest)(nil),    // 0: main.CacheGetRequest
	(*CacheGetResponse)(nil),   // 1: main.CacheGetResponse
	(*CacheSetRequest)(nil),    // 2: main.CacheSetRequest
	(*CacheDeleteRequest)(nil), // 3: main.CacheDeleteRequest
	(*emptypb.Empty)(nil),      // 4: google.protobuf.Empty
}
var file_cache_pkg_api_grpc_proto_schema_cache_proto_depIdxs = []int32{
	0, // 0: main.CacheService.Get:input_type -> main.CacheGetRequest
	2, // 1: main.CacheService.Set:input_type -> main.CacheSetRequest
	3, // 2: main.CacheService.Delete:input_type -> main.CacheDeleteRequest
	1, // 3: main.CacheService.Get:output_type -> main.CacheGetResponse
	4, // 4: main.CacheService.Set:output_type -> google.protobuf.Empty
	4, // 5: main.CacheService.Delete:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cache_pkg_api_grpc_proto_schema_cache_proto_init() }
func file_cache_pkg_api_grpc_proto_schema_cache_proto_init() {
	if File_cache_pkg_api_grpc_proto_schema_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDesc), len(file_cache_pkg_api_grpc_proto_schema_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_pkg_api_grpc_proto_schema_cache_proto_goTypes,
		DependencyIndexes: file_cache_pkg_api_grpc_proto_schema_cache_proto_depIdxs,
		MessageInfos:      file_cache_pkg_api_grpc_proto_schema_cache_proto_msgTypes,
	}.Build()
	File_cache_pkg_api_grpc_proto_schema_cache_proto = out.File
	file_cache_pkg_api_grpc_proto_schema_cache_proto_goTypes = nil
	file_cache_pkg_api_grpc_proto_schema_cache_proto_depIdxs = nil
}
