// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/api/grpc/proto/schema/analytics.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClickEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	ClickedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=clickedAt,proto3" json:"clickedAt,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=userAgent,proto3" json:"userAgent,omitempty"`
	Referer       string                 `protobuf:"bytes,5,opt,name=referer,proto3" json:"referer,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickEvent) Reset() {
	*x = ClickEvent{}
	mi := &file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickEvent) ProtoMessage() {}

func (x *ClickEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickEvent.ProtoReflect.Descriptor instead.
func (*ClickEvent) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_schema_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *ClickEvent) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *ClickEvent) GetClickedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClickedAt
	}
	return nil
}

func (x *ClickEvent) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *ClickEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ClickEvent) GetReferer() string {
	if x != nil {
		return x.Referer
	}
	return ""
}

func (x *ClickEvent) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_schema_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *StatsRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShortCode      string                 `protobuf:"bytes,1,opt,name=shortCode,proto3" json:"shortCode,omitempty"`
	TotalClicks    int64                  `protobuf:"varint,2,opt,name=totalClicks,proto3" json:"totalClicks,omitempty"`
	UniqueVisitors int64                  `protobuf:"varint,3,opt,name=uniqueVisitors,proto3" json:"uniqueVisitors,omitempty"`
	ClickedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=clickedAt,proto3,oneof" json:"clickedAt,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_grpc_proto_schema_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *StatsResponse) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *StatsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *StatsResponse) GetUniqueVisitors() int64 {
	if x != nil {
		return x.UniqueVisitors
	}
	return 0
}

func (x *StatsResponse) GetClickedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClickedAt
	}
	return nil
}

var File_pkg_api_grpc_proto_schema_analytics_proto protoreflect.FileDescriptor

const file_pkg_api_grpc_proto_schema_analytics_proto_rawDesc = "" +
	"\n" +
	")pkg/api/grpc/proto/schema/analytics.proto\x12\x04main\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\n" +
	"ClickEvent\x12\x1c\n" +
	"\tshortCode\x18\x01 \x01(\tR\tshortCode\x128\n" +
	"\tclickedAt\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tclickedAt\x12\x1c\n" +
	"\tipAddress\x18\x03 \x01(\tR\tipAddress\x12\x1c\n" +
	"\tuserAgent\x18\x04 \x01(\tR\tuserAgent\x12\x18\n" +
	"\areferer\x18\x05 \x01(\tR\areferer\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\",\n" +
	"\fStatsRequest\x12\x1c\n" +
	"\tshortCode\x18\x01 \x01(\tR\tshortCode\"\xc4\x01\n" +
	"\rStatsResponse\x12\x1c\n" +
	"\tshortCode\x18\x01 \x01(\tR\tshortCode\x12 \n" +
	"\vtotalClicks\x18\x02 \x01(\x03R\vtotalClicks\x12&\n" +
	"\x0euniqueVisitors\x18\x03 \x01(\x03R\x0euniqueVisitors\x12=\n" +
	"\tclickedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\tclickedAt\x88\x01\x01B\f\n" +
	"\n" +
	"_clickedAt2\x85\x01\n" +
	"\x10AnalyticsService\x127\n" +
	"\vRecordClick\x12\x10.main.ClickEvent\x1a\x16.google.protobuf.Empty\x128\n" +
	"\rGetStatistics\x12\x12.main.StatsRequest\x1a\x13.main.StatsResponseB\tZ\a.;protob\x06proto3"

var (
	file_pkg_api_grpc_proto_schema_analytics_proto_rawDescOnce sync.Once
	file_pkg_api_grpc_proto_schema_analytics_proto_rawDescData []byte
)

func file_pkg_api_grpc_proto_schema_analytics_proto_rawDescGZIP() []byte {
	file_pkg_api_grpc_proto_schema_analytics_proto_rawDescOnce.Do(func() {
		file_pkg_api_grpc_proto_schema_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_grpc_proto_schema_analytics_proto_rawDesc), len(file_pkg_api_grpc_proto_schema_analytics_proto_rawDesc)))
	})
	return file_pkg_api_grpc_proto_schema_analytics_proto_rawDescData
}

var file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_api_grpc_proto_schema_analytics_proto_goTypes = []any{
	(*ClickEvent)(nil),            // 0: main.ClickEvent
	(*StatsRequest)(nil),          // 1: main.StatsRequest
	(*StatsResponse)(nil),         // 2: main.StatsResponse
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_pkg_api_grpc_proto_schema_analytics_proto_depIdxs = []int32{
	3, // 0: main.ClickEvent.clickedAt:type_name -> google.protobuf.Timestamp
	3, // 1: main.StatsResponse.clickedAt:type_name -> google.protobuf.Timestamp
	0, // 2: main.AnalyticsService.RecordClick:input_type -> main.ClickEvent
	1, // 3: main.AnalyticsService.GetStatistics:input_type -> main.StatsRequest
	4, // 4: main.AnalyticsService.RecordClick:output_type -> google.protobuf.Empty
	2, // 5: main.AnalyticsService.GetStatistics:output_type -> main.StatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_grpc_proto_schema_analytics_proto_init() }
func file_pkg_api_grpc_proto_schema_analytics_proto_init() {
	if File_pkg_api_grpc_proto_schema_analytics_proto != nil {
		return
	}
	file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_grpc_proto_schema_analytics_proto_rawDesc), len(file_pkg_api_grpc_proto_schema_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_grpc_proto_schema_analytics_proto_goTypes,
		DependencyIndexes: file_pkg_api_grpc_proto_schema_analytics_proto_depIdxs,
		MessageInfos:      file_pkg_api_grpc_proto_schema_analytics_proto_msgTypes,
	}.Build()
	File_pkg_api_grpc_proto_schema_analytics_proto = out.File
	file_pkg_api_grpc_proto_schema_analytics_proto_goTypes = nil
	file_pkg_api_grpc_proto_schema_analytics_proto_depIdxs = nil
}
